// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"github.com/palp1tate/go-zero-demo/service/user/internal/logic"
	"github.com/palp1tate/go-zero-demo/service/user/internal/svc"
	"github.com/palp1tate/go-zero-demo/service/user/pb"
)

type UserSrvServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserSrvServer
}

func NewUserSrvServer(svcCtx *svc.ServiceContext) *UserSrvServer {
	return &UserSrvServer{
		svcCtx: svcCtx,
	}
}

func (s *UserSrvServer) Login(ctx context.Context, in *pb.LoginRequest) (*pb.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserSrvServer) Register(ctx context.Context, in *pb.RegisterRequest) (*pb.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}
